base_url = "https://simoncoudeville.be"
title = "Simon Coudeville"
description = "Personal blog of Simon Coudeville"
compile_sass = true
build_search_index = false

[markdown]
highlight_code = true
# highlight_theme = "gray-matter-dark"
highlight_theme = "css"

[extra]
# blog_date_format = "%e %b %Y"
# blog_date_format = "%e %B %Y"
blog_date_format = "%b %e, %Y"
# blog_date_format = "%B %o, %Y"
# blog_date_format = "%F"
# blog_date_format = "%b %e, %Y"
# blog_date_format = "%m.%d.%Y"
